### ISSUE TITLE
config helper function

### ISSUE THREAD

**Issue by n3vrax** [JapSeyz/Dot-migrations#1]
Hi,

I think the latest release introduced a bug in the config helper function.
Keeping track of the current file prevents infinite loops but it seems you cannot read from the same file multiple times now.

**Comment by JapSeyz** [comment]
Okay, I'll take a look at it. I will probably have to also keep track of the lastet key. I'll fix it when I am back from vacation.

**Comment by JapSeyz** [comment]
@n3vrax Can you submit a PR for this, it seems to be an issue with your use-case. Calling the file multiple times from itself will always result in a lot of recursion and something like dot-env should be used instead to prevent this.
